spring.application.name=web-shop
spring.application.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/webshop_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.docker.compose.enabled=false
spring.jpa.hibernate.ddl-auto=create-drop

# --- Configuration ---
# --- Remote API ---
app.erp.remote.url=http://host.docker.internal:4004/rest/api/products
app.erp.remote.username=alice
app.erp.remote.password=alice
app.erp.remote.call.period=0 * * * * *

# --- Local storage path ---
app.files.products.path=/opt/app/data/products.json

# --- Admin credentials ---
web.shop.admin.email=admin@webshop.com
web.shop.admin.password=admin

# --- environment ---
spring.profiles.active=erp

# --- RabbitMQ Configuration ---
spring.rabbitmq.host=host.docker.internal
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# --- RabbitMQ Queues
app.queues.order-request=orders.request
app.queues.order-response=orders.response
app.queues.order-error=orders.error